edition = "2021"
max_width = 110
use_small_heuristics = "Max"
wrap_comments = true
comment_width = 100
imports_granularity = "Crate"
newline_style = "Windows"
normalize_comments = true
reorder_imports = true
format_code_in_doc_comments = true
